version: "3"
services:
  mysql8:
    image: mysql:8.0.29
    restart: always
    command:
      #      - 加入参数，设置 binlog 和主节点
      - --default_authentication_plugin=mysql_native_password
      - --binlog-format=ROW
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      #      - 外部访问用 13316
      - "3308:3306"
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
  mongo:
    image: mongo:6.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
  etcd:
    image: "bitnami/etcd:latest"
    restart: always
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - "12379:2379"