version: "3"
# 我这个 docker compose 由几个服务组成
services:
  mysql8:
    image: mysql:8.0.29
    restart: always
    command:
      #      - 加入参数，设置 binlog 和主节点
      - --default_authentication_plugin=mysql_native_password
      - --binlog-format=ROW
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      #      - 外部访问用 13316
      - "3308:3306"
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"