apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: webook-mysql-pvc
spec:
  storageClassName: manual
  # 访问模式 不能被多个Pod读写
  accessModes:
    - ReadWriteOnce
  # 需要的存储资源大小
  resources:
    requests:
      storage: 1Gi